// src/components/Maze.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Button, Container, Divider, Icon, Label, Message } from 'semantic-ui-react';
import MazeCell from './MazeCell';
import Point from '../models/Point';
import StackItem from '../models/StackItem';
import { MAZE_CELL } from '../Constants';
import Util from '../Util';

class Maze extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      maze: props.maze,
      player: Util.getPlayerState(props.maze),
      solved: false,
      solution: null,
      error: null,
    };

    this.handleKeyPress = this.handleKeyPress.bind(this);
    this.solveMaze = this.solveMaze.bind(this);
    this.handleSolveMaze = this.handleSolveMaze.bind(this);
    this.renderError = this.renderError.bind(this);
    this.renderSolution = this.renderSolution.bind(this);
  }

  componentWillMount() {
    document.addEventListener('keydown', this.handleKeyPress);
  }

  static renderRow(row, i) {
    return (
      <div className="maze-row" key={i}>
        {row.map((cell, j) => (
          <MazeCell value={cell} key={`${i}-${j}`} />
        ))}
      </div>
    );
  }

  /**
   * Changes the player state
   * @param {PlayerState} newPlayerState
   */
  setNewPlayerState(newPlayerState) {
    this.setState(prevState => {
      let stillSolved = false;
      let newSolution = [];
      let newMaze = Util.mazeWithUpdatedPlayerState(
        prevState.maze,
        prevState.player,
        newPlayerState
      );
      if (newPlayerState.location.equals(prevState.player.location)) {
        stillSolved = prevState.solved;
        newSolution = prevState.solution;
      } else if (prevState.solution) {
        if (newPlayerState.location.equals(prevState.solution[0])) {
          stillSolved = true;
          newSolution = prevState.solution.slice(1);
        } else {
          stillSolved = false;
          newSolution = null;
          newMaze = Util.mazeWithClearedHighlightedPath(newMaze, prevState.solution);
        }
      }
      return {
        maze: newMaze,
        player: newPlayerState,
        solved: stillSolved,
        solution: newSolution,
      };
    });
  }

  /**
   * Moves the player forward one square in the direction they are facing, if the target cell is free
   */
  moveForward() {
    const targetCell = this.state.player.forwardLocation();

    if (Util.isFree(targetCell, this.state.maze)) {
      this.setNewPlayerState(this.state.player.moveForward());
    }
  }

  rotateRight() {
    this.setNewPlayerState(this.state.player.rotateRight());
  }

  rotateLeft() {
    this.setNewPlayerState(this.state.player.rotateLeft());
  }

  rotateBack() {
    this.setNewPlayerState(this.state.player.rotateBack());
  }

  /**
   * Solves the maze and returns the path to the exit
   */
  solveMaze() {
    const steps = [p => p.left(), p => p.right(), p => p.up(), p => p.down()];
    const stack = [new StackItem(this.state.player.location, 0)];
    const exit = new StackItem(new Point(-1, -1), Infinity);

    const _maze = Util.deepCopy(this.state.maze);

    switch (this.state.player.direction) {
      case MAZE_CELL.PLAYER.RIGHT:
        Util.swap(steps[1], steps[0]);
        break;
      case MAZE_CELL.PLAYER.DOWN:
        Util.swap(steps[3], steps[0]);
        break;
      case MAZE_CELL.PLAYER.UP:
        Util.swap(steps[2], steps[0]);
        break;
      default:
        break;
    }

    while (stack.length > 0) {
      const si = stack.pop();
      for (const step of steps) {
        const posAfter = step(si.pos);
        if (Util.isOutOfBounds(posAfter, _maze)) continue;

        const block = _maze[posAfter.x][posAfter.y];
        if (Util.isFree(posAfter, _maze) || (typeof block === 'number' && block > si.dist + 1)) {
          stack.push(new StackItem(posAfter, si.dist + 1));
          _maze[posAfter.x][posAfter.y] = si.dist + 1;
          if (Util.isExit(posAfter, _maze) && si.dist + 1 < exit.dist) {
            exit.pos = posAfter;
            exit.dist = si.dist + 1;
          }
        }
      }
    }

    if (exit.dist === Infinity) {
      return null;
    }

    return Util.getPath(_maze, exit);
  }

  handleKeyPress(event) {
    switch (event.code) {
      case 'ArrowUp':
        this.moveForward();
        break;
      case 'ArrowLeft':
        this.rotateLeft();
        break;
      case 'ArrowRight':
        this.rotateRight();
        break;
      case 'ArrowDown':
        this.rotateBack();
        break;
      default:
        break;
    }
  }

  handleSolveMaze() {
    const path = this.solveMaze();
    if (!path) {
      this.setState({
        solved: false,
        error: 'There is no way out :(',
      });
    } else {
      this.setState(prevState => ({
        solved: true,
        solution: path,
        maze: Util.mazeWithHighlightedPath(prevState.maze, path),
      }));
    }
  }

  renderError() {
    if (!this.state.error) {
      return null;
    }
    return <Message error>{this.state.error}</Message>;
  }

  renderSolution() {
    if (!this.state.solved) {
      return null;
    }
    return (
      <Message
        floating
        size="big"
        header="Directions"
        content={Util.pathDirections(this.state.solution, this.state.player)}
      />
    );
  }

  static renderControls() {
    return (
      <Container className="controls-container" textAlign="center">
        <Label>
          <Icon size="big" name="arrow alternate circle up" />
          Move forward
        </Label>
        <Label>
          <Icon size="big" name="arrow alternate circle left" />
          Rotate left
        </Label>
        <Label>
          <Icon size="big" name="arrow alternate circle right" />
          Rotate right
        </Label>
        <Label>
          <Icon size="big" name="arrow alternate circle down" />
          Rotate 180 degrees
        </Label>
      </Container>
    );
  }

  render() {
    return (
      <Container>
        <Container textAlign="center">{Maze.renderControls()}</Container>
        <Container>{this.state.maze.map((row, i) => Maze.renderRow(row, i))}</Container>
        <Divider hidden />
        <Container textAlign="center">
          <Button primary onClick={this.handleSolveMaze} disabled={this.state.solved}>
            Solve maze
          </Button>
          {this.renderSolution()}
          {this.renderError()}
        </Container>
      </Container>
    );
  }
}

Maze.propTypes = {
  maze: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.string)).isRequired,
};

export default Maze;

// src/app/maze/maze.component.ts
import { Component, OnInit, Input, HostListener } from '@angular/core';

const PLAYER_LEFT = '<';
const PLAYER_RIGHT = '>';
const PLAYER_UP = '^';
const PLAYER_DOWN = 'v';
const WALL = '#';
const FREE = ' ';
const ROTATE_BACK = 'B';
const ROTATE_LEFT = 'L';
const ROTATE_RIGHT = 'R';
const MOVE_FORWARD = 'F';

@Component({
  selector: 'app-maze',
  templateUrl: './maze.component.html',
  styleUrls: ['./maze.component.css']
})
export class MazeComponent implements OnInit {
  @Input()
  mazeString: string[];


  private mazeSolution: string[];
  private solved: boolean;
  private playing: boolean;
  private playerPos: Point;
  public maze: any[];

  constructor() {
    this.playerPos = new Point(-1, -1);
    this.solved = false;
    this.playing = false;
   }

  ngOnInit() {
    this.maze = [];

    for (let i = 0; i < this.mazeString.length; i++) {
      this.maze[i] = [];
      for (let j = 0; j < this.mazeString[i].length; j++) {
        this.maze[i].push(this.mazeString[i][j]);
        const p = new Point(i, j);
        if (this.isPlayer(p)) {
          this.playerPos = p;
        }
      }
    }
  }

  @HostListener('window:keyup', ['$event'])
  keyEvent(event: KeyboardEvent) {
    if(this.playing) {
      return;
    }
    switch(event.code) {
      case 'ArrowUp': this.moveForward(true); break;
      case 'ArrowLeft': this.rotateLeft(true); break;
      case 'ArrowRight': this.rotateRight(true); break;
      case 'ArrowDown': this.rotateBack(true); break;
    }
  }

  public updateSolution(): void {
    this.mazeSolution = this.getPath();
    this.clearMaze();
  }

  private delay(ms: number) {
    return new Promise( resolve => setTimeout(resolve, ms) );
  }

  public async playSolution() {
    this.solved = false;
    this.playing = true;
    for(let move of this.mazeSolution) {
      this.playMove(move);
      await this.delay(500);
    }
    this.playing = false;
  }

  public playMove(move: string): void {
    switch(move) {
      case MOVE_FORWARD: this.moveForward(); break;
      case ROTATE_BACK: this.rotateBack(); break;
      case ROTATE_LEFT: this.rotateLeft(); break;
      case ROTATE_RIGHT: this.rotateRight(); break;
    }
  }

  private isFree(p: Point): boolean {
    if (this.isOutOfBounds(p)) {
      return false;
    }
    return this.maze[p.x][p.y] === FREE;
  }

  private isWall(p: Point): boolean {
    if (this.isOutOfBounds(p)) {
      return false;
    }
    return this.maze[p.x][p.y] === WALL;
  }

  private isExit(p: Point): boolean {
    if (this.isOutOfBounds(p)) {
      return false;
    }
    return p.x === 0 || p.y === 0 || p.x === this.maze.length - 1 || p.y === this.maze[0].length - 1;
  }

  private isPlayer(p: Point): boolean {
    if (this.isOutOfBounds(p)) {
      return false;
    }
    return !this.isFree(p) && !this.isWall(p);
  }

  private isOutOfBounds(p: Point): boolean {
    return p.x < 0 || p.x >= this.maze.length || p.y < 0 || p.y >=this.maze[0].length;
  }

  private moveForward(userAction: boolean = false): void {
    let targetCell: Point;
    const state = this.maze[this.playerPos.x][this.playerPos.y];
    
    switch(state) {
      case PLAYER_LEFT: targetCell = this.left(this.playerPos); break;
      case PLAYER_RIGHT: targetCell = this.right(this.playerPos); break;
      case PLAYER_DOWN: targetCell = this.down(this.playerPos); break;
      case PLAYER_UP: targetCell = this.up(this.playerPos); break;
    }

    if (this.isFree(targetCell)) {
      this.maze[targetCell.x][targetCell.y] = state;
      this.maze[this.playerPos.x][this.playerPos.y] = FREE;
      this.playerPos = targetCell;
    }

    if(userAction) {
      this.solved = false;
    }
  }

  private rotateLeft(userAction: boolean = false): void {
    const state = this.maze[this.playerPos.x][this.playerPos.y];
    switch(state) {
      case PLAYER_LEFT: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_DOWN; break;
      case PLAYER_RIGHT: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_UP; break;
      case PLAYER_DOWN: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_RIGHT; break;
      case PLAYER_UP: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_LEFT; break;
    }

    if(userAction) {
      this.solved = false;
    }
  }

  private rotateRight(userAction: boolean = false): void {
    const state = this.maze[this.playerPos.x][this.playerPos.y];
    switch(state) {
      case PLAYER_LEFT: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_UP; break;
      case PLAYER_RIGHT: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_DOWN; break;
      case PLAYER_DOWN: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_LEFT; break;
      case PLAYER_UP: this.maze[this.playerPos.x][this.playerPos.y] = PLAYER_RIGHT; break;
    }

    if(userAction) {
      this.solved = false;
    }
  }

  private rotateBack(userAction: boolean = false): void {
    this.rotateLeft(userAction);
    this.rotateLeft(userAction);
  }

  private left(p: Point): Point {
    return new Point(p.x, p.y - 1);
  } 

  private right(p: Point): Point {
    return new Point(p.x, p.y + 1);
  }

  private up(p: Point): Point {
    return new Point(p.x - 1, p.y);
  }

  private down(p: Point): Point {
    return new Point(p.x + 1, p.y);
  }

  /**
   * Solves the maze and returns the exit point
   */
  private solveMaze(): StackItem {
    const steps = [this.left, this.right, this.up, this.down];
    const stack: StackItem[] = [new StackItem(this.playerPos, 0)];
    let exit: StackItem = new StackItem(new Point(-1, -1), Infinity);

    //let clone = JSON.parse(JSON.stringify(this.maze));

    let state = this.maze[this.playerPos.x][this.playerPos.y];
    switch(state) {
      case PLAYER_RIGHT: this.swap(steps[1], steps[0]); break;
      case PLAYER_DOWN: this.swap(steps[3], steps[0]); break;
      case PLAYER_UP: this.swap(steps[2], steps[0]); break;
    }

    while(stack.length > 0) {
      const si = stack.pop();
      for(let step of steps) {
        const posAfter = step(si.pos);
        if(this.isOutOfBounds(posAfter)) continue;

        const block = this.maze[posAfter.x][posAfter.y];
        if(this.isFree(posAfter) || (typeof(block) === 'number' && block > si.dist + 1) ) {
          stack.push(new StackItem(posAfter, si.dist + 1));
          this.maze[posAfter.x][posAfter.y] = si.dist + 1;
          if(this.isExit(posAfter) && si.dist + 1 < exit.dist){
            exit.pos = posAfter;
            exit.dist = si.dist + 1;
          }
        }
      }
    }

    return exit;
  }

  /**
   * Gets an array of characters corresponding to the directions to the exit. If there is no exit returns an empty array
   */
  private getPath(): string[] {
    const exit = this.solveMaze();
    if(exit.dist === Infinity) {
      this.solved = false;
      if(this.isExit(this.playerPos)) {
        return ["You are already at the exit"];
      }
      return ["There is no solution for this maze."];
    }
    this.solved = true;

    const steps = [this.left, this.right, this.up, this.down];
    const path = [exit.pos];
    let result = [];

    let currentPos = exit.pos;
    let distance = exit.dist;

    while (distance > 1) {
      for (let step of steps) {
        const posAfter = step(currentPos);
        if(!this.isOutOfBounds(posAfter) && this.maze[posAfter.x][posAfter.y] === distance - 1) {
          path.push(posAfter);
          currentPos = posAfter;
          distance--;
          break;
        }
      }
    }
    
    currentPos = this.playerPos;
    let state = this.maze[this.playerPos.x][this.playerPos.y];

    for(let i = path.length - 1; i >= 0; i--) {
      const r = this.rotate(currentPos, path[i], state);
      if(r[0]) {
        result.push(r[0]);
      }
      state = r[1];
      result.push(MOVE_FORWARD);
      currentPos = path[i];
    }

    return result;
  }

  private clearMaze(): void {
    for(let i = 0; i < this.maze.length; i++) {
      for (let j = 0; j < this.maze[i].length; j++) {
        if(typeof(this.maze[i][j]) === 'number') {
          this.maze[i][j] = FREE;
        }
      }
    }
  }

  private rotate(from: Point, to: Point, state: string): string[] {
    let rotation;
    let stateAfterRotation = state;

    if (to.equals(this.left(from))) {
      stateAfterRotation = PLAYER_LEFT;
      switch(state) {
        case PLAYER_RIGHT: rotation = ROTATE_BACK; break;
        case PLAYER_DOWN: rotation = ROTATE_RIGHT; break;
        case PLAYER_UP: rotation = ROTATE_LEFT; break;
      }
    }
    else if (to.equals(this.right(from))) {
      stateAfterRotation = PLAYER_RIGHT;
      switch(state) {
        case PLAYER_LEFT: rotation = ROTATE_BACK; break;
        case PLAYER_DOWN: rotation = ROTATE_LEFT; break;
        case PLAYER_UP: rotation = ROTATE_RIGHT; break;
      }
    }
    else if (to.equals(this.up(from))) {
      stateAfterRotation = PLAYER_UP;
      switch(state) {
        case PLAYER_LEFT: rotation = ROTATE_RIGHT; break;
        case PLAYER_DOWN: rotation = ROTATE_BACK; break;
        case PLAYER_RIGHT: rotation = ROTATE_LEFT; break;
      }
    }
    else if (to.equals(this.down(from))) {
      stateAfterRotation = PLAYER_DOWN;
      switch(state) {
        case PLAYER_LEFT: rotation = ROTATE_LEFT; break;
        case PLAYER_UP: rotation = ROTATE_BACK; break;
        case PLAYER_RIGHT: rotation = ROTATE_RIGHT; break;
      }
    }

    return [rotation, stateAfterRotation];
  }

  private swap(a: object, b: object): void {
    const tmp = b;
    b = a;
    a = tmp;
  }
}

class Point {
  x: number;
  y: number;

  constructor(x: number, y: number) {
    this.x = x;
    this.y = y;
  }

  public equals(other: Point) {
    return this.x === other.x && this.y === other.y;
  }
}

class StackItem {
  pos: Point;
  dist: number;

  constructor(pos: Point, dist: number) {
    this.pos = pos;
    this.dist = dist;
  }
}

<div class="container">
  <h2>Controls: </h2>
  <fa-icon icon="arrow-up"></fa-icon> <span>Move forward</span>
  <fa-icon icon="arrow-left"></fa-icon> <span>Rotate left</span>
  <fa-icon icon="arrow-right"></fa-icon> <span>Rotate right</span>
  <fa-icon icon="arrow-down"></fa-icon> <span>Rotate back</span>
</div>
<br><br>
<div class="container">
  <div class="row" *ngFor="let row of maze">
    <app-maze-cell *ngFor="let cell of row" [cellType]="cell"></app-maze-cell>
  </div>
</div>
<br>
<div class="container">
  <textarea class="form-control" rows="1" readonly>{{mazeSolution}}</textarea>
  <br>
  <button [disabled]="solved || playing" type="button" class="btn btn-primary" (click)="updateSolution()">Solve maze</button>
  <button [disabled]="!solved || playing" type="button" class="btn btn-primary" (click)="playSolution()">Play solution</button>
</div>
